//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uygulama
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public byte PersonelD { get; set; }
        public string PersonelAD { get; set; }
        public string PersonelSoyad { get; set; }
        public string PersonelMaas { get; set; }
        public string PersonelTC { get; set; }
        public string PersonelDepartman { get; set; }
    }
}
